name: MammaMia
main: amata1219.mamma.mia.MammaMia
version: 1.0.1
api-version: '1.21.4'
softdepend: [Essentials]
author: '@amata1219'

commands:
  mamiya:
    permission: mamiyer.mamiya
    permission-message: 'You don''t have <permission>'